language: node_js
node_js:
- '6'
after_success: npm run coverage
deploy:
  provider: npm
  email: fptavares@gmail.com
  api_key:
    secure: 3csQ1q8B99VorjP2geLpSTkXR+Zy2keLa7vozaPbY0DeDtIVc8B/aD7lkNJ22SuEVtLDk4pC3MtIQzVk0TA6JqAM2rlFxDtPkU2JnQvqMQD/gEJfGDTeb2QuaN/ESTs3jJhMJ0CxzPLLRu6wloCPCVKIEQ30ed5MQBNynfO7mcPrtjn3scwDIy1Op4Aa/JxEj1D2BO8sVlc5eGZE1QIDMK+g0z1ZSbMwNJpR2c1iz3JlzEuj+kQqT8o+mB8RZp31puzMsXRUQ/E6Tt/YJefRT5bEIPeYAY+HllykexIO6/KXrRQGUijezCsTm2tqzOFGGPVn/VQo0S2+YhoFMIlMmzSB/t+znYLaeQnag+Ya8dDs6oFGGejzjqKm5qFr3iNnpoWRPfVgrZInlidwK2FhsiK99dm5h++CyqZ8JUSfvWnJowI00kpvUUZpFWYXcAp3t3+6ERl5nV6s0CYDSjufMFwDBO7w3wF6R6EXuQKxo/pdI3YPVRkiIxP9vBeIV6DDx3id6g1Pf+nYsGvs7+3ewZ9oMx5cidSpZYymH3bNvvz0AnxIhplvey+4NFdjdm8SS6TwlY8QfDOoCkS+C6JUS/ZO3TGIr98lTMYidz4XcPy3a5n4njnJNMFzITI5F6OS4bmlx6nj62zgnrmPkSnySHWmlm5Y/QlJ8hasFUlnN7Y=
  on:
    tags: true
    repo: fptavares/modofun
